// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_BVwbAhFll1VX4o6UXcFrfKT_YcIiqAQ',
    appId: '1:107740208794:web:e977327b71e6e946800923',
    messagingSenderId: '107740208794',
    projectId: 'btlnhom2-4660e',
    authDomain: 'btlnhom2-4660e.firebaseapp.com',
    databaseURL: 'https://btlnhom2-4660e-default-rtdb.firebaseio.com',
    storageBucket: 'btlnhom2-4660e.firebasestorage.app',
    measurementId: 'G-47Z7J15ENC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfWzt1HJGbIGm21vI8M2gskM1UBejc3f0',
    appId: '1:107740208794:android:3b7a4c106b5d2337800923',
    messagingSenderId: '107740208794',
    projectId: 'btlnhom2-4660e',
    databaseURL: 'https://btlnhom2-4660e-default-rtdb.firebaseio.com',
    storageBucket: 'btlnhom2-4660e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYsgtbP6ZjBT-7Wsl-pepHMDriWGbniLQ',
    appId: '1:107740208794:ios:e55375880771460f800923',
    messagingSenderId: '107740208794',
    projectId: 'btlnhom2-4660e',
    databaseURL: 'https://btlnhom2-4660e-default-rtdb.firebaseio.com',
    storageBucket: 'btlnhom2-4660e.firebasestorage.app',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYsgtbP6ZjBT-7Wsl-pepHMDriWGbniLQ',
    appId: '1:107740208794:ios:e55375880771460f800923',
    messagingSenderId: '107740208794',
    projectId: 'btlnhom2-4660e',
    databaseURL: 'https://btlnhom2-4660e-default-rtdb.firebaseio.com',
    storageBucket: 'btlnhom2-4660e.firebasestorage.app',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_BVwbAhFll1VX4o6UXcFrfKT_YcIiqAQ',
    appId: '1:107740208794:web:ab91e6cf1e7d77e6800923',
    messagingSenderId: '107740208794',
    projectId: 'btlnhom2-4660e',
    authDomain: 'btlnhom2-4660e.firebaseapp.com',
    databaseURL: 'https://btlnhom2-4660e-default-rtdb.firebaseio.com',
    storageBucket: 'btlnhom2-4660e.firebasestorage.app',
    measurementId: 'G-CMS8PCSBNK',
  );
}
